### ISSUE TITLE
Would you consider packaging release here on GH?

### ISSUE THREAD

**Issue by schwim0341** [Knoot/FastGuildInvite#1]
Hello there!

For those of us using a third party addon manager that can no longer install your addon due to the Curse API change, would you consider posting releases with the zip file so we can install from URL and purge the Curse link?

Thanks for your consideration!

**Comment by Knoot** [comment]
Hello.

I will consider this possibility.

**Comment by Knoot** [comment]
https://github.com/Knoot/FastGuildInvite/releases/tag/102

Subsequent updates are set to automatically create a release on github

**Comment by schwim0341** [comment]
Thanks so much!
