### ISSUE TITLE
On WoW Clients without translation default is russian language

### ISSUE THREAD

**Issue by gOOvER** [Knoot/FastGuildInvite#1]
I'm on german client. As default is russian language. Pls use only the english translation as default and fallback language and not russian.

Plugin cant be used on WoW Clients, where is no translation provided

**Comment by Knoot** [comment]
If the "SYSTEM" section is not translated for your language, the search will not work correctly.

In the latest version, the language is automatically selected.
First, all the translated values for your language are collected, then the missing ones are borrowed from the translations for the English version, and if both options are missing, Russian is used.
