### ISSUE TITLE
Lua

### ISSUE THREAD

**Issue by reaper666735** [Knoot/FastGuildInvite#2]
hello, 

got these today:

1x ...uildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0-154.lua:919: attempt to index field 'Result' (a nil value)
...uildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0-154.lua:919: in function `ProcessWhoResults'
...uildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0-154.lua:897: in function `?'
...uildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0-154.lua:932: in function <...uildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:931>

Locals:
self = <table> {
 GetNextFromScheduler = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:377
 ReturnWho = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:502
 Cache = <table> {
 }
 UserInfo = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:179
 MinInterval = 2.500000
 CachedUserInfo = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:260
 SetWhoToUIState = false
 WHOLIB_QUEUE_QUIET = 2
 AskWhoNextIn5sec = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:329
 CapitalizeInitial = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:737
 CancelPendingWhoNext = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:337
 PossibleEvents = <table> {
 }
 Timeout_time = -0.000000
 embeds = <table> {
 }
 hooked = <table> {
 }
 ProcessWhoResults = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:912
 WHO_LIST_UPDATE = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:903
 AllQueuesEmpty = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:314
 CHAT_MSG_SYSTEM = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:895
 RegisterCallback = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 CheckCallback = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:675
 TriggerEvent = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:750
 UnregisterCallback = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 DupAll = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:725
 ConsoleWho = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:610
 Embed = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:291
 Dup = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:711
 WHOLIB_FLAG_ALWAYS_CALLBACK = 1
 simple_dump = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:701
 GetQueryInterval = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:327
 external = <table> {
 }
 callbacks = <table> {
 }
 CheckArgument = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:647
 RaiseCallback = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:637
 MaxInterval = 10
 AskWho = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:494
 GuiWho = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:592
 Library = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:304
 ReturnUserInfo = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:631
 AskWhoNext = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:409
 L = <table> {
 }
 queue_bounds = <table> {
 }
 UnregisterAllCallbacks = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UpdateWeights = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:358
 Total = 1
 Debug = false
 SetWhoLibDebug = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:276
 CheckPreset = <function> defined @FastGuildInvite\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0.lua:657
 GetWhoLibDebug = <function> defi

**Comment by Knoot** [comment]
search your add-ons folder, find the file "LibWho-2.0-154.lua"
this file is missing in the FGI addon, apparently another addon connects the LibWho library earlier

**Comment by Knoot** [comment]
the problem is resolved
