### ISSUE TITLE
Message and Invite not sending messages 4.4.0

### ISSUE THREAD

**Issue by LynkOne** [Knoot/FastGuildInvite#4]
The option Send a message and invite is not working with last release 123.

Messages are being sent with options Message only and Message if invitation is declined.

**Comment by Knoot** [comment]
this is due to the lack of a message when inviting someone to the guild. And this is on Blizzard's side.

**Comment by LynkOne** [comment]
Modified function invitePlayer and now its working :)

> function fn:invitePlayer(noInv)
	local list = addon.search.inviteList
	if #list==0 then return end
	-- if IsInAlreadySendedList(list[1].name) then return table.remove(list, 1) end
	if (DB.global.inviteType == 2 or DB.global.inviteType == 4) and not noInv then
		addon.msgQueue[list[1].name] = true
		if (DB.global.inviteType == 2) then
			fn:sendWhisper(list[1].name)
		end
	elseif DB.global.inviteType == 3 and not noInv then
		fn:sendWhisper(list[1].name)
	end
	if (DB.global.inviteType == 1 or DB.global.inviteType == 2 or DB.global.inviteType == 4) and not noInv then
		debug(format("Invite: %s",list[1].name))
		GuildInvite(list[1].name)
	end
	if not noInv or DB.global.rememberAll then
		fn:rememberPlayer(list[1].name)
		local data = fn.encodeData({
			type = "REMEMBER",
			playerName = list[1].name
		})
		ChatThrottleLib:SendAddonMessage("NORMAL", FGISYNC_PREFIX_G, data, "GUILD")
	end
	if not noInv then
		addon.searchInfo.sended()
		fn.history:onSend();
	end
	table.remove(list, 1)
	onListUpdate()
end

**Comment by LynkOne** [comment]
Justt add
		if (DB.global.inviteType == 2) then
			fn:sendWhisper(list[1].name)
		end

**Comment by Knoot** [comment]
there's no problem getting it to work "any way". But this solution ignores the existing logic
