### ISSUE TITLE
Cant invite over level 70

### ISSUE THREAD

**Issue by blastyduke** [Knoot/FastGuildInvite#5]
In setting we can choose to invite between level 1 to 80 but it still stop at level 70.  The query in who dont get pass this as example : 70-70 r-"Draenei" c-"Monk"

Thank you for you help I tried looking in .lua file and edit FGI_Constants to change lin 145 to FGI_MAXLVL = 80 but still not working.

**Comment by Knoot** [comment]
this "problem" is related to remembering the list of search queries. When changing the range of search levels, you need to reset the search. "Reset" in the main window or "R" in the scan window

**Comment by blastyduke** [comment]
OK my bad it works like a charm now:) thank you
